### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by balibou** [DesignmanIO/react-native-meteor-redux#10]
Thanks for this amazing package !

Is there any chance to get a simple example repo to see how it is working ?
Plus, is it working with react-native-meteor authentication (like passing a user object to initialState in redux) ?

Again thanks a lot !

**Comment by JulianKingman** [comment]
Sure, I'll set something up :)

I'm not clear on what your second question means, but anything that was stored by `react-native-meteor` will added to redux (and persisted, if you're using `redux-persist`). If you want to know whether the user is logged in when the app starts, however, you can check for the login token, which is saved to AsyncStorage by `react-native-meteor`.

**Comment by balibou** [comment]
Ahah great !

For the second point here is an explanation concerning authentication (note that I can get the token from Asyncstorage without redux, but I need to keep a user object when offline and set it at initialstate):

- Firstly, I tried to use redux-persist without your package, but the thing is I have problem with the calculateData() from Mixin.js in react-native-meteor ...
- Secondly I tried with your package, but I have a problem retrieving states from redux (undefined states).

**Comment by JulianKingman** [comment]
I added an example app, courtesy of @spencercarli's boilerplate (https://github.com/spencercarli/react-native-meteor-boilerplate). Search the example project tree for 'react-native-meteor-redux' and you'll find all the places I changed the code.

**Comment by JulianKingman** [comment]
FYI there's a fix in the latest one, so try to update to 1.1.12, then let me know if you still have an issue.

**Comment by balibou** [comment]
Perfect ! Thanks a lot I will try that as soon as possible !

i think I have already installed the package in 1.1.12. I will check my code again ...
Thanks again !

**Comment by JulianKingman** [comment]
The latest example will actually let you log in now :)
