### ISSUE TITLE
undefined is not an object (evaluating '_reactNativeMeteor2.default.ddp.status')

### ISSUE THREAD

**Issue by balibou** [DesignmanIO/react-native-meteor-redux#11]
Hello,
I get this error when launching the app (I use the last version of the package 1.1.12):

<img width="377" alt="screen shot 2017-02-18 at 19 28 32" src="https://cloud.githubusercontent.com/assets/7440159/23096281/b58e6486-f610-11e6-9af4-d869c66b77a8.png">

**Comment by balibou** [comment]
[FIXED] Weird, it has been fixed when starting the JS debugging ...

**Comment by JulianKingman** [comment]
Ah, there's a mistake on my end that contributes to this, it will be fixed in 1.1.13
