### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): XXXXXXXXX is undefined

### ISSUE THREAD

**Issue by balibou** [DesignmanIO/react-native-meteor-redux#12]
Note: 
- XXXXXXXXX is the real id of the current user.
- The app was already running with a current user before installing the package.

[FIXED]
- I have uninstalled the app on the simulator.
- I did a meteor reset on meteor.
- I quit xcode then recompile the app and reinstalled it.
- Then I created a whole new user.

**Comment by JulianKingman** [comment]
What version are you using? Also what's the code in question, and do you have any more details about the error?

**Comment by balibou** [comment]
Version 1.1.12
Sorry didn't do a screenshot.

**Comment by JulianKingman** [comment]
I think I see the issue. Should be fixed in 1.1.13
