### ISSUE TITLE
User object format persistence

### ISSUE THREAD

**Issue by balibou** [DesignmanIO/react-native-meteor-redux#13]
It should be interesting to persist the user object differently.
Now it is persisted like this (with a property named with the userID):

<img width="219" alt="screen shot 2017-02-18 at 21 16 05" src="https://cloud.githubusercontent.com/assets/7440159/23096961/f1897f16-f61f-11e6-9b2f-41243e3e0c47.png">

**Comment by balibou** [comment]
PLUS: is there another to get the persisted user object (offline) other than using MeteorStore.getState() ?

**Comment by JulianKingman** [comment]
How would you suggest? Collections are keyed by _id for performance.

**Comment by balibou** [comment]
In fact this is linked with [#14](https://github.com/DesignmanIO/react-native-meteor-redux/issues/14).

If the user object should be accessed through props in component (and is not null), then this issue #13 is deprecated.

**Comment by JulianKingman** [comment]
OK, I'll take care of #14 and close this.
