### ISSUE TITLE
Possible Unhandled Promise Rejection (id:0): undefined is not an object

### ISSUE THREAD

**Issue by balibou** [DesignmanIO/react-native-meteor-redux#19]
I think it is related with those changes you did : https://github.com/DesignmanIO/react-native-meteor-redux/commit/0b14856423ac56c15eb44965a9162ad38ae1e76a

Here is the screen:

![unnamed](https://cloud.githubusercontent.com/assets/7440159/23335143/d4e22a2a-fba6-11e6-98e9-436fa0f8fa6f.png)

**Comment by JulianKingman** [comment]
Ah, stupid mistake. Try 1.1.20
