### ISSUE TITLE
some info on current limitations pls

### ISSUE THREAD

**Issue by adamgins** [DesignmanIO/react-native-meteor-redux#2]
@JulianKingman thanks again

about to try this... just wanted to ensure I understood 

> Note that this currently returns all documents, and find queries won't work. I hope to fix that soon.

Does this mean if you do something like `returnCached(Meteor.collection('docs').find({some:value}), MeteorStore, 'docs');` it will be the same as `returnCached(Meteor.collection('docs').find({}), MeteorStore, 'docs');` ?

Also if you have different subscriptions that subscribe to different sub-sets of data, there just stored in the separate variable, right?

eg Subs 1 returns `Collection1.find({status:true})` & Subs 2 returns `Collection1.find({somefield:123})` you'll return via multiple returnCached statements?

**Comment by JulianKingman** [comment]
returnCached is literally caching all the docs you find. So if you just have one find query, it's quite straightforward, it caches the docs returned by that find. If you have two different find queries on the same collection, it will 'merge' them, and you'll need to filter them out manually.

For subscriptions, if you use something like Grapher, or Publish-Composite to rename the collection on a per-subscription basis, then it will store those separately as if they were unique data sets. MeteorCache listens to DDP, so if subscriptions are changed, the cached data will change.

Does that answer everything?

**Comment by JulianKingman** [comment]
No longer relevant with the new API
