### ISSUE TITLE
[Realm branch] Document.fields must be of type: string

### ISSUE THREAD

**Issue by balibou** [DesignmanIO/react-native-meteor-redux#22]
<img width="377" alt="screen shot 2017-03-04 at 16 39 07" src="https://cloud.githubusercontent.com/assets/7440159/23580426/a853018e-00f9-11e7-9466-bfb379662bdf.png">

**Comment by JulianKingman** [comment]
Hang tight, I'm working on getting the example working.

**Comment by balibou** [comment]
ahah ok I let you work on the repo sorry for my over attendance on the repo :D

**Comment by JulianKingman** [comment]
Try the latest push

**Comment by balibou** [comment]
ok

**Comment by JulianKingman** [comment]
No worries, I really appreciate the help. I have an app that I'd really like to take offline, but can't yet for perf reasons.

**Comment by balibou** [comment]
lol it's exactly the same for me ...

**Comment by balibou** [comment]
Because I didn't succeed to run you package with npm link, I just copy/paste to node_modules for now ... I am encountering the bug of babel presets ... I have created the .babelrc but it doesn't seem to work ...

**Comment by JulianKingman** [comment]
You can include the package like how it is in the example's package.json (`"react-native-meteor-redux": "DesignmanIO/react-native-meteor-redux#realm"`). Try that, then clean and try again.

**Comment by balibou** [comment]
Oh great you're right I can install it that way !
But I still have the error with presets ...

**Comment by JulianKingman** [comment]
What's the error specifically?

**Comment by balibou** [comment]
<img width="375" alt="screen shot 2017-03-04 at 18 33 22" src="https://cloud.githubusercontent.com/assets/7440159/23581293/223a2b44-0109-11e7-9c8d-b7c229ea8517.png">

**Comment by JulianKingman** [comment]
If you're running the example, it has the es2015 as a dev dependency, so it should install with the package. I'll add it as a dependency for the package, but in the meantime just do `npm i --save-dev babel-preset-es2015`

**Comment by balibou** [comment]
perfect cheers :)
Now I came back to the first error Document.fields must be of type: string lol

**Comment by JulianKingman** [comment]
OK, I think I fixed it, try re-installing.

**Comment by balibou** [comment]
Mmm no same error still

**Comment by JulianKingman** [comment]
That's really weird. Everything is stringified before being saved, so I'm not sure how that could even happen. Anything unusual about your data? Try uninstalling and reinstalling your app on the simulator, maybe some bad data got in there somehow.

**Comment by balibou** [comment]
Yeah weird, exactly same error again

**Comment by balibou** [comment]
[FIXED] I've stopped my meteor server and it's working ...

If I run the server it crashes ...

**Comment by JulianKingman** [comment]
Random thought, does initmeteorrealm come before or after meteor.connect? Try fiddling with that?

**Comment by balibou** [comment]
Before ahah because I import it from another file ...
I will try to put it after ...

**Comment by balibou** [comment]
Before or after it's the same ...

**Comment by balibou** [comment]
Ok when I render the app for the first time I have the error, then when I refresh the app there is no more bug ...

**Comment by JulianKingman** [comment]
Hm, well I can't reproduce it, so not sure what to tell you...

**Comment by balibou** [comment]
no worries, I'll try to provide you an example for this one

**Comment by balibou** [comment]
I just added you as collaborator on the 2 repos for this error.

For the meteor one:
- run meteor npm i
- npm start (give me your email for sending you the settings json file)
(maybe there will be an error at first launch so disconnect and reconnect)

For the RN one (branch test-with-initMeteorRealm):
- yarn
- then run ios

[Note] : When I disconnect meteor server, the RN app can launch, then I reconnect meteor there is no bug. But as soon as I refresh the RN app it bugs again ...

Thx :)

**Comment by JulianKingman** [comment]
Email: julian @ designman.io

**Comment by JulianKingman** [comment]
On the meteor side, I get ` While selecting package versions:
   error: unknown package in top-level dependencies: balibou:accounts-phone`

**Comment by balibou** [comment]
I will send it to you in 8 hours :)

**Comment by balibou** [comment]
yeah for that error `While selecting package versions: error: unknown package in top-level dependencies: balibou:accounts-phone` try to reconnect the server, then it should be good

**Comment by JulianKingman** [comment]
Nm, found your github repo (you should change the bcrypt version, package name, and remove the `dist` folder)

**Comment by balibou** [comment]
mmm are you sure it's the good repo ? I don't see any dist folder ... FeelChat (meteor or RN repo)

**Comment by JulianKingman** [comment]
I think it's not up-to-date, can you update your accounts-phone package to match what you're using locally?

**Comment by balibou** [comment]
yeah will do that when coming back home 
thanks :)

**Comment by philohelp** [comment]
Hi there, sorry to interrupt. Just to let you know I have the same Document.fields error while connected to a distant Meteor server. Is that bad timing ? Holes in the dataset ? I had ids but no emails for some sentries but then I filled the holes and reinitialized the simulator and got the same error.
I wish I could help !

**Comment by JulianKingman** [comment]
Interesting, so it works on localhost?

**Comment by JulianKingman** [comment]
Stopping work on the realm branch for now.

**Comment by balibou** [comment]
Thanks for all the amazing job you did on this branch :)
