### ISSUE TITLE
Could customised combine reducers be injected to createStore?

### ISSUE THREAD

**Issue by Diwei-Chen** [DesignmanIO/react-native-meteor-redux#25]
Thank you so much for your efforts on this project.

Recently, we are developing a react native app based on this library and wondering if there is a way that we could inject our customised reducers to initMeteorRedux Method or createStore method? Then we could be able to make use of the reducers to dispatch actions as the way we want?

**Comment by JulianKingman** [comment]
You should be able to pass in `combineReducers` as with a normal store. `initMeteorRedux` basically just wraps `createStore` and passes in the params.

**Comment by adamgins** [comment]
@JulianKingman thanks for the quick response. 

being a noob to RN + Redux... it would be good to get an example/more info pls.

From what I can see the `createStore` in `initMeteorRedux` is hardwired to `meteorReduxReducers` as per https://github.com/DesignmanIO/react-native-meteor-redux/blob/master/connectMeteorRedux.js#L85

Are you saying I should fork the package and add another param, so we can pass in non-Meteor reducers or use some other mechanism?

thanks

@Diwei-Chen

**Comment by JulianKingman** [comment]
Ah, yes you are right, I was thinking of when I was initially testing it. Thanks for the PR.
