### ISSUE TITLE
Data Loss after SET_READY

### ISSUE THREAD

**Issue by Diwei-Chen** [DesignmanIO/react-native-meteor-redux#28]
<img width="514" alt="222" src="https://cloud.githubusercontent.com/assets/26317142/24328419/f7c07ce6-1234-11e7-8535-b293c23c7363.png">

Hi @JulianKingman , we use a combine reducers in the initialisation of store and the user reducer is our customised reducer as shown above. After persist/REHYDRATE and SET_READY actions, I am confused why the userObj stored in state would be lost?

Regards,

**Comment by JulianKingman** [comment]
First question is, do you have any reducers with these names? `ADDED`, `CHANGED`, `REMOVED`, `SET_READY`, `persist/REHYDRATE`, `HARDRESET`?

**Comment by Diwei-Chen** [comment]
This issue is caused by not properly storing data to reducers.
