### ISSUE TITLE
Current redux state is not written to disk properly

### ISSUE THREAD

**Issue by Diwei-Chen** [DesignmanIO/react-native-meteor-redux#29]
Hi @JulianKingman , how are you doing? we meet an issue that current redux state cannot properly/correctly be written disk which leads to a wrong rehydration.. The process can be seen as follows:
1. We have one resource to show which is stored in resources collection
![screen shot 2017-03-30 at 6 25 11 pm](https://cloud.githubusercontent.com/assets/26317142/24492197/3ed5958c-1576-11e7-9a07-c6b1afed426b.png)

![screen shot 2017-03-30 at 6 11 28 pm](https://cloud.githubusercontent.com/assets/26317142/24491743/55c89cbe-1574-11e7-9cbf-64c03d6f0165.png)

2. After we add one more resource to database and delete it, everything works correctly.
![screen shot 2017-03-30 at 6 13 48 pm](https://cloud.githubusercontent.com/assets/26317142/24491833/d4b1c712-1574-11e7-8ca1-6b2deb551c25.png)

![screen shot 2017-03-30 at 6 14 27 pm](https://cloud.githubusercontent.com/assets/26317142/24491842/dcfaabe6-1574-11e7-9531-10e18c8e1a23.png)

3. But after we refresh the app, current redux state is rehydrated to the state after we added the second resource.
![screen shot 2017-03-30 at 6 18 36 pm](https://cloud.githubusercontent.com/assets/26317142/24491965/5934c598-1575-11e7-9ec7-d091d52cd904.png)
![screen shot 2017-03-30 at 6 19 04 pm](https://cloud.githubusercontent.com/assets/26317142/24491974/62f89afa-1575-11e7-9043-3b49b7953683.png)

Is this because redux-persist doesn't write the current redux state to disk properly or we hit command + R which is hot reload and just happen in simulator? Any suggestions, please?

Here is the persistStore configuration:
`const persistor = persistStore(MeteorStore, {
  storage: AsyncStorage,
  keyPrefix: 'react-native-meteor-redux',
  debounce: 1000
}, () => {
  MeteorStore.loaded();
});`

Regards,

**Comment by JulianKingman** [comment]
You're not doing anything wrong, that's an issue with the way it's currently written (#24). After a connection is restored, it should (but doesn't) diff the collections. It's a difficult problem, because you want to store any documents that have been accessed, not just those from the current subscription.
To accomplish this, I'll have to store each subscription and a list of documents it includes. I don't think this will be too hard or expensive, we'll see. props go to GroundDB for solving a similar problem (https://github.com/GroundMeteor/subscriptions/blob/master/subscriptions.client.js). Let me give this a shot, maybe I can fix #27 while I'm at it.

**Comment by Diwei-Chen** [comment]
Thanks Julian. Much appreciated. 

We think this library saves us a lot of work and is really useful to us. 

We look forward to seeing the updates.

Thanks,

**Comment by JulianKingman** [comment]
Great :)

It turns out subscription info is not really available for individual documents, as they're all combined on the server by the publications. I'll give this some more thought.

**Comment by Diwei-Chen** [comment]
Hi @JulianKingman , how is it going? Do you need any help with it?

**Comment by adamgins** [comment]
Hi @JulianKingman wondering if you've had any more thought on this or a better approach package to deal with offline?

**Comment by JulianKingman** [comment]
Sorry I've been MIA, it's been a busy few weeks and I haven't had an immediate need for this. I've got an update that will improve performance quite a bit, and I'll add a 'dumb' implementation for removing docs at least, until I can figure out a smart one.

**Comment by JulianKingman** [comment]
This should be working/fixed in v 2.0

**Comment by Diwei-Chen** [comment]
Cool. This works perfectly in our project. 

Thank you very much, Julian.

Much appreciated.
