### ISSUE TITLE
Clear all the data in the store

### ISSUE THREAD

**Issue by suryaiiit** [DesignmanIO/react-native-meteor-redux#31]
Hi,

Thanks for the package, it works perfectly fine.

I'm trying to clear all the data that is stored when the user Logouts using the below:
`MeteorStore.dispatch({ type: 'HARDRESET' })`

Where MeteorStore is the store, as given in the example.
It removes everything but when I refresh the app all the data is back there in the state, any other way with which we can remove all the data as there is no point in storing the data once the user logouts.

Once again Thank you.

**Comment by JulianKingman** [comment]
Probably the easiest way to do this is to call `purge` on the persister, like this:
````javascript
const MeteorStore = initMeteorRedux(undefined, autoRehydrate());
const persister = persistStore(MeteorStore, { storage: AsyncStorage, debounce: 1000 }, () => {
  MeteorStore.loaded();
});
MeteorStore.dispatch({ type: 'HARDRESET' })
persister.purge();
````

**Comment by rasmushjulskov** [comment]
Trying to clear local data aswell. Shouldn't the following work @JulianKingman:
```js
import MeteorOffline from 'react-native-meteor-redux';
const MO = new MeteorOffline({debounce: 1000});

MO.store.dispatch({ type: 'HARDRESET' });
MO.persister.purge();
```

**Comment by JulianKingman** [comment]
Yep, it should
