### ISSUE TITLE
How to write record

### ISSUE THREAD

**Issue by trancaohuy** [DesignmanIO/react-native-meteor-redux#38]
Thank you for the great package. Do you have any sample codes that illustrate the writing of records back to Meteor offline and while online?
thank you

**Comment by JulianKingman** [comment]
Hi @trancaohuy, the package doesn't handle inserts or updates while offline, it's somewhat complicated and will take more time than I have available for this project, particularly as I haven't needed the functionality. If you want to insert or update while offline, I recommend creating a task que that runs when you come online again, you may also need to check to see if other updates have run.

If you (or anyone) are interested in making a PR, that'd be awesome.

**Comment by JulianKingman** [comment]
See https://github.com/DesignmanIO/react-native-meteor-offline/issues/41#issuecomment-332794693 for how I recommend handling this.
