### ISSUE TITLE
[Error] Expected listener to be a function 

### ISSUE THREAD

**Issue by WayneUong** [DesignmanIO/react-native-meteor-redux#39]
My code:
```
export default createContainer(() => {
    GroundedMeteor.subscribe('links.all', 'links.all.id');

    return {
        links: GroundedMeteor.collection('links', 'links.all').find(),
        status: Meteor.status(),
    };
}, App);
```
![simulator screen shot jun 30 2017 10 29 52 pm](https://user-images.githubusercontent.com/8436742/27759347-a8ca3104-5de3-11e7-8fa4-9d916e20463f.png)

**Comment by WayneUong** [comment]
Fixed by chaging
`import MeteorOffline from 'react-native-meteor-redux';`
to
`import initMeteorRedux, { MeteorOffline } from 'react-native-meteor-redux';`

**Comment by tquiroga** [comment]
What does `initMeteorRedux` look like?
