### ISSUE TITLE
can't install on new project

### ISSUE THREAD

**Issue by UADACID** [DesignmanIO/react-native-meteor-redux#4]
![simulator screen shot jan 23 2017 10 33 52 am](https://cloud.githubusercontent.com/assets/15373307/22190683/8885e784-e157-11e6-9bed-f3f0a5d8e267.png)

I followed the instructions how to install but the library is unreadable in node_modul,

**Comment by JulianKingman** [comment]
Did you try the fixes it suggests?
https://github.com/facebook/react-native/issues/4968

Also, please update to the latest version (1.1.5 as of this writing), `npm update react-native-meteor-redux -S`

**Comment by radiegtya** [comment]
although using 1.1.6 it can't be running. Because u r missing "events" module.

Btw I am already send PR here:
https://github.com/DesignmanIO/react-native-meteor-redux/pull/5

**Comment by radiegtya** [comment]
should be closed @UADACID @JulianKingman
