### ISSUE TITLE
How to sync inserts/updates after resuming connection

### ISSUE THREAD

**Issue by krunaldodiya** [DesignmanIO/react-native-meteor-redux#41]
just like in whatsapp,

if we dont have internet access, it will still let us type and when click send it will display message store locally in device abut not sync to server unless device has internet connection back.

i am really new, want to achieve this function.. it is working when internet.. also offline working as well when i quit application and stop internet, still shows old data.. but after that, if i go to chat box and type and press enter, nothing happens.. atleast how to store it in local redux and persist untll internet connection back and start sync :)

**Comment by JulianKingman** [comment]
Currently offline creation is out-of-scope for this package. Maybe at some point I (or someone) will work more intensely with this package and create a PR for that feature. In the meantime, you could create a sort of custom "task que" using redux, and then us a callback to determine when to execute them (i.e. `Meteor.ddp.on('connected', function() {})`).
The thing that makes this difficult to implement (and the reason I haven't already) is syncing documents edited by multiple people. It's very difficult to know how to synchronize.

**Comment by krunaldodiya** [comment]
okay thanks for information :)

**Comment by JulianKingman** [comment]
I added a helper function `subReady`. This allows you to get a subscription's status anywhere in the app. My recommendation is to use it to prevent updates, etc..., something like this:
```javascript
import {Alert} from 'react-native';
import {MO} from '../somewhere';

// ... somewhere in a component
insertDoc (doc) {
  if (MO.subReady('myUniqueSubscriptionName') {
    Meteor.collection('pages').insert(doc);
  } else {
    Alert.alert('Sorry!', 'Wait until you\'re online before inserting pages');
  }
  render() {
    // or something like this:
    if (!MO.subReady('myUniqueSubscriptionName') return <Text>Sorry, no insert offline</Text>;
    return <Text onPress={() => this.insertDoc()}>Insert page</Text>;
}
```
