### ISSUE TITLE
'cleared' field ignored in ddp event listeners

### ISSUE THREAD

**Issue by you-fail-me** [DesignmanIO/react-native-meteor-redux#44]
More of a question, than an issue. I've noticed that in ddp event listener, which reacts to the `CHANGED` event, only the `fields` prop of the event obj is respected. But the `CHANGED` event also happens with `cleared` property,  which is an array of fields of the doc, which were unset, i.e. cleared. No action is taken in response to `CHANGED` events with `cleared` payload.
Is that on purpose? If yes, why?

**Comment by JulianKingman** [comment]
I don't think I noticed that, I'll check that out when I get a minute (or feel free to make a PR). So it sends a separate `cleared` object?

**Comment by you-fail-me** [comment]
the shape is the same, but instead of `fields` property on the event obj you have `cleared` property which is an array of strings, corresponding to the names of the cleared fields of the doc

**Comment by JulianKingman** [comment]
I added handling for cleared in 2.2.2 https://github.com/DesignmanIO/react-native-meteor-offline/commit/4ccfae4af4ca89590a0fb4d36569d942b468e42f
