### ISSUE TITLE
with expo sdk32 : invalid attempt to spread non-iterable instance

### ISSUE THREAD

**Issue by lc3t35** [DesignmanIO/react-native-meteor-redux#58]
![image](https://user-images.githubusercontent.com/921372/52918587-0db93d80-32f9-11e9-87b2-d2bc2987d051.png)

It happens in connectMeteorRedux
```
case 'RECENTLY_ADDED': {
      return {
        ...state,
        reactNativeMeteorOfflineRecentlyAdded: [
          ...(state.reactNativeMeteorOfflineRecentlyAdded || []),
          id,
        ],
      };
}
``

**Comment by lc3t35** [comment]
I think you need to check if reactNativeMeteorOfflineRecentlyAdded is undefined or empty before spread : 
```
if (state.reactNativeMeteorOfflineRecentlyAdded === undefined || state.reactNativeMeteorOfflineRecentlyAdded.length === 0) {
   return {
      ...state, 
      reactNativeMeteorOfflineRecentlyAdded: [id]
   }
} else {
   return {
        ...state,
        reactNativeMeteorOfflineRecentlyAdded: [
          ...state.reactNativeMeteorOfflineRecentlyAdded,
          id,
        ],
   };
}
```

**Comment by lc3t35** [comment]
Still NOT FIXED .... fails at
```
} else {
        return {
          ...state,
          reactNativeMeteorOfflineRecentlyAdded: [
            ...state.reactNativeMeteorOfflineRecentlyAdded,     <<<<<<==== HERE
            id,
          ],
        };
      }
```

**Comment by alexpricedev** [comment]
Same issue here! Following

**Comment by alexpricedev** [comment]
I did a little debugging and it seems like after a reconnect, the `state.reactNativeMeteorOfflineRecentlyAdded` is an object with indexed keys, rather than an array like normal:

```
{0: "C9yHHgvBeahxpBNRz", ...}
```

which is pretty fishy, because the state shouldnt have been mutated...

**Comment by lc3t35** [comment]
Thank you @remotealex, this what I was about to check, but you found it before me, thank you very much ! I will try this asap. stay tuned ....

**Comment by lc3t35** [comment]
Issue seems to be fixed.
