### ISSUE TITLE
null is not an object (evaluating 'state.hasOwnProperty')

### ISSUE THREAD

**Issue by radiegtya** [DesignmanIO/react-native-meteor-redux#7]
I think my code already same with example but I am ussing connectMeteor instead createContainer. And it produce above error. Here are my code:

```javascript
  getMeteorData(){
    const sub = subscribeCached(MeteorStore, 'account', this.selector(), this.options());

    return {
      // ready: handle.ready()
    }
  }

  selector(){
    const search = this.state.search;
    return {
      'name': {$regex: search, $options: "i"},
    };
  }

  options(){
    return {limit: this.state.limit, sort: {createdAt: -1}};
  }
```

here is the complete error:

<img width="320" alt="2017-01-25_0825" src="https://cloud.githubusercontent.com/assets/2161622/22274281/1947feac-e2d8-11e6-9a92-38b4b9df1315.png">

edit:
I have tried using createContainer but still same error, so I think thats not the cause

Note:
I am not really good at Redux stuff.
please help

**Comment by JulianKingman** [comment]
Did you do the initialization part? I.e.
````javascript
// myReduxStuff.js
import initMeteorRedux from 'react-native-meteor-redux';
import {AsyncStorage} from 'react-native';
import {persistStore, autoRehydrate} form 'redux-persist';

const MeteorStore = initMeteorRedux(null, autoRehydrate());

// Pick your storage option, I used AsyncStorage which makes sense for react-native
persistStore(MeteorStore, {storage: AsyncStorage}, () => {
  // Callback tells minimongo to use MeteorStore until connectivity is restored
  MeteorStore.loaded()
});

export {MeteorStore}
````

**Comment by radiegtya** [comment]
of course I did with the same syntax as above

**Comment by radiegtya** [comment]
any info about this @JulianKingman ?

**Comment by JulianKingman** [comment]
Ok, obvious question, are you importing MeteorStore on your component? It looks like for some reason the persister is not recognizing the redux store.

**Comment by radiegtya** [comment]
of course I did something basic like that. I am using RN 0.40. All just the same with your example. if I don't import MeteorStore, ofc the error will be undefined MeteorStore in line x.

**Comment by UADACID** [comment]
I also have to follow the instructions as in demonstrated, but got the same error as above, please check back in the your example

**Comment by JulianKingman** [comment]
Ah, try passing `undefined` instead of `null` for the first param in `initMeteorRedux`

**Comment by radiegtya** [comment]
well done! thanks @JulianKingman .. its fixed now.
I'll try dig deeper using this package, if I found something strange again in more advance usage, I'll inform you..

**Comment by radiegtya** [comment]
btw the error had gone using undefined, but it encountered warning like this.

<img width="320" alt="2017-01-30_0813" src="https://cloud.githubusercontent.com/assets/2161622/22409926/1b161f4e-e6c4-11e6-9e6f-2410154a0070.png">

is this normal or we can remove this warning? @JulianKingman

**Comment by JulianKingman** [comment]
Hmm, can you trace it to anything particular? I don't think I have any promises in the code.
