### ISSUE TITLE
undefined is not an object (evaluating 'state[collection]')

### ISSUE THREAD

**Issue by UADACID** [DesignmanIO/react-native-meteor-redux#8]
<img width="310" alt="screen shot 2017-01-30 at 1 54 09 pm" src="https://cloud.githubusercontent.com/assets/15373307/22414662/eb37ab0a-e6f3-11e6-854e-fabb11501eff.png">

I get a warning like the picture above, and cause the project can not be built for release, on emulator running normally but request on my application still feels  heavy

**Comment by JulianKingman** [comment]
Try v1.1.11
What are your Babel settings? If v1.1.11 doesn't fix it, it may be that I need to add some babel dependencies.

**Comment by JulianKingman** [comment]
sorry about that, fixed in v1.1.12

**Comment by UADACID** [comment]
Thx, i will try again 😄
