### ISSUE TITLE
Slow when the dataset large

### ISSUE THREAD

**Issue by radiegtya** [DesignmanIO/react-native-meteor-redux#9]
I have slow experience when using android and force close when using ios (deployed version) when my database collection are relative huge. Is this because AsyncStorage only have 6mb Storage or there are another cause? If it was because AsyncStorage, can u give example or alternative what storage can be used and how to implement it?

**Comment by JulianKingman** [comment]
This is a good question that I don't fully know the answer to. I'm tracking a potentially related issue here: https://github.com/rt2zz/redux-persist/issues/185

I think it's related to AsyncStorage, since it has to serialize and de-serialize everything before it's saved. An alternative would be to use realm.io, but I haven't tested it yet, and you need a schema (for my current use-case defining a schema would be a problem). Redux persist describes how to add a different kind of store, it seems pretty straightforward.

The easiest solution is to not access so much data. Why do you need to store so much?

**Comment by radiegtya** [comment]
For example a chat app would need large storage to save message when used at daily basis. Or we can remove existing cached?

**Comment by JulianKingman** [comment]
This will cache whatever you subscribe. So in this example, you could have individual subscriptions for each person, and only subscribe to the 50 most recent messages (as you'll find most apps do this). Now your max size is only 50, even if you have many subscriptions. I would imagine that would help?

**Comment by radiegtya** [comment]
ofc I did that with limited subs, but when data subscribed everyday, automatically it will get bigger.
Btw is this package can be used as offline sync?
and btw android still force close although I have increase the max storage to 500mb

**Comment by balibou** [comment]
I get exactly the same problem, however my dataset is only 200 contacts, and it takes few seconds to render the page ...

**Comment by balibou** [comment]
I tried all the week end to resolve this issue but apparently it's really impossible.
On the top of that, Asyncstorage documentation says (https://facebook.github.io/react-native/docs/asyncstorage.html): 

> It is recommended that you use an abstraction on top of AsyncStorage instead of AsyncStorage directly for anything more than light usage since it operates globally.

Maybe it should be good to move away from Asyncstorage and use an abstraction store for scoping data like : 
[react-native-simple-store](https://github.com/jasonmerino/react-native-simple-store).

explained [here](https://codepen.io/asommer70/post/react-native-saving-habits)

**Comment by balibou** [comment]
Mmm ... Finally it doesn't sounds good, because updating the store with react-native-simple-store is deep merging object ... so lack of performance ...

**Comment by balibou** [comment]
[SOLUTION]
@JulianKingman  @radiegtya 
It sounds that the solution to this problem will be [Realm](https://realm.io/).
Here is an explanation of the stack: https://medium.com/@bosung90/tackling-react-native-storage-part-1-d27b2bfa480f#.b0ghiyxih

Thoughts ?
Any possibility to implement it ?

**Comment by JulianKingman** [comment]
It's possible, and I've tried it. Unfortunately, it still runs slow for me, I think I'm doing something wrong somewhere... In any case, it does run twice as fast. If you can get it to work well, let me know, I've uploaded a new branch with the realm stuff I have so far.

**Comment by balibou** [comment]
OK I will try with that [repo](https://github.com/bosung90/RNStorage) too

**Comment by balibou** [comment]
I will definitely focus on realm from now on. Asyncstorage is unfortunately not the best solution for meteor collections.

**Comment by balibou** [comment]
ok I think I know how to improve performance with realm: we need to remove redux-persist.

**Comment by balibou** [comment]
@JulianKingman  question:
Have you tried using realm just with the basic usage and not with redux-persist : 
```js
import initMeteorRedux from 'react-native-meteor-redux';

const MeteorStore = initMeteorRedux(initialState, enhancers);

// Now you can access MeteorStore as a redux store throughout your app.
export {MeteorStore};
```

**Comment by JulianKingman** [comment]
In the realm branch, I added `initMeteorRealm`, which takes an `options` parameter, like so:
````javascript
import {initMeteorRealm} from 'react-native-meteor-redux';

// blacklist = collections to not cache
const MeteorStore = initMeteorRealm({blacklist: 'example_collection'});
export {MeteorStore};
````

It doesn't use redux or persist, actually. Also make sure you run `react-native link` after installing, since realm has some native linking requirements.

**Comment by balibou** [comment]
Ok thx I will test it as soon as possible, cheers

**Comment by balibou** [comment]
I'm encountering this [issue](https://github.com/facebook/react-native/issues/10882) when I make a yarn link ... 

How do you run your package ?

**Comment by JulianKingman** [comment]
I think you have to use 'react-native link', but I don't use yarn, so not entirely sure. What version of RN are you on? It used to be `rnpm link`, but rnpm was absorbed by react-native core. It should show you logs confirming that realm is linked. You could also try deleting the node_modules folder and running yarn install again.

**Comment by balibou** [comment]
Yeah my app is already linked with react-native-meteor-redux (status OK in the terminal).
React Native version: 0.39.2
I also tried deleting the node_modules folder and running yarn install again ...

**Comment by JulianKingman** [comment]
Did you run `react-native link` with the realm branch? Realm is the package that needs to be linked. If you're running on android, you may need to do more setup: https://realm.io/docs/javascript/latest/#getting-started
I'll set up the example to run with realm.

**Comment by balibou** [comment]
Yeah I ran `react-native link` with the realm branch.
I run it on ios simulator.
ok thanks for the example :)

**Comment by balibou** [comment]
Interesting discussion I've spotted: https://github.com/realm/realm-js/issues/435

**Comment by balibou** [comment]
[FIX?]
react-native-meteor is using minimongo-cache. In the README package ([minimongo-cache](https://github.com/petehunt/minimongo-cache)) here is an explanation of low perf:

> `minimongo-cache` defaults to debug mode which enables long stack traces. These are great for debugging but can be slow. Set db.debug = false to disable this feature.

Also here is a list of perf improvements:
- Favor db.get() over db.find() or db.findOne()
- Set db.batchedUpdates = React.addons.batchedUpdates
- Use shouldComponentUpdate() with minimongo-cache's identity feature

Have you tried this for your performance issues @JulianKingman ?

**Comment by JulianKingman** [comment]
I updated the example, it's working for me locally, give it a shot. I'll look into the debug mode thing, that's a good tip.

**Comment by JulianKingman** [comment]
Ah, nice try, but `react-native-meteor` already turns off debug mode and uses the batchedUpdates feature. `db.get` is handy for single documents, and `shouldComponentUpdate` is a good tip when UI re-renders are the problem, but I've found they are not the main problem. I'm curious what the identity feature is, though, do you know?

**Comment by balibou** [comment]
Mmm I did some research on the identity feature and nothing relevant ...
The only meaning to that is the id of the object associated by mongo/minimongo ...

**Comment by JulianKingman** [comment]
Version 2.0 should be much faster and has a new API, check it out.

**Comment by JulianKingman** [comment]
I think the speed is pretty reasonable now, so I'm closing this.
